### ISSUE TITLE
Gathering Data for local analysis

### ISSUE THREAD

**Issue by dominikponniah** [farscrl/dicziunari#5]
I am trying to investigate a bit to recreate the App as a Web-Application for Desktops.
But I have a strange problem regarding following the documentation and therefore some questions:

- Where is the Data located in the `app`-Directory? (Or, where do I have to place the file at?)
- Trying to generate the File for placing it into the `app`-Directory I am getting the following error:
`gitpod /workspace/dicziunari/db $ npm run convert

> dicziunari-tools@1.0.0 convert
> node ./src/index.js

Start converting JSON file for Rumantsch Grischun...
/workspace/dicziunari/db/node_modules/better-sqlite3/lib/database.js:47
                throw new TypeError('Cannot open database because the directory does not exist');
                ^

TypeError: Cannot open database because the directory does not exist`

Could you eventually help me with this?

Cheers! And ä guata rutsch!

**Comment by gion-andri** [comment]
Hi @dominikponniah , 
thanks for reching out. 

I have updated the README files, hopefully it is clearer now where to put the database files. 

Unfortunately we are not yet allowed to publish the database on GitHub - but we are working on making this possible in the future. 

Regarding your questions: 
* In the `app` folder you have to put the DB here: `app/src/assets/databases/dicziunariSQLite.db`
* For `db` project, a build folder is expected, but it was not checked in so far. If you update the project, this should work now. You can just rename the template DB file in the build folder, so you don't have to create an empty DB yourself. 

I hope this helps for now. Otherwise just tell us. 

Allas guati fürs 2022!
